import type { ReactNode } from 'react';
import type { Metadata } from 'next';

import Navigation from '../components/Navigation';
import { albertSans, arOneSans } from '../lib/fonts';
import '../styles/global.css';

export const metadata: Metadata = {
  title: 'Welcome to my-happy-bunch',
  description: 'Generated by create-nx-workspace',
};
const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en" className={`${arOneSans.variable} ${albertSans.variable}`}>
      <body>
        <header className="bg-gray-800">
          <Navigation />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
